// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJGhoXb-pmNYiR30d9mtgG5ivlgtdFKlc',
    appId: '1:246504893636:web:027ba5db695b7e865ded91',
    messagingSenderId: '246504893636',
    projectId: 'onenation-hub-924d1',
    authDomain: 'onenation-hub-924d1.firebaseapp.com',
    storageBucket: 'onenation-hub-924d1.firebasestorage.app',
    measurementId: 'G-RHM51CY7WN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBDeOL9mSB78SOhWlURZWQ5s_rABUEO3A',
    appId: '1:246504893636:android:eac3d456c2b83a745ded91',
    messagingSenderId: '246504893636',
    projectId: 'onenation-hub-924d1',
    storageBucket: 'onenation-hub-924d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK4ZZiPRhUR_j6DQb5ylMUEIGNgznDBO4',
    appId: '1:246504893636:ios:c3ae02ecdc8106685ded91',
    messagingSenderId: '246504893636',
    projectId: 'onenation-hub-924d1',
    storageBucket: 'onenation-hub-924d1.firebasestorage.app',
    iosBundleId: 'com.example.onenationHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK4ZZiPRhUR_j6DQb5ylMUEIGNgznDBO4',
    appId: '1:246504893636:ios:c3ae02ecdc8106685ded91',
    messagingSenderId: '246504893636',
    projectId: 'onenation-hub-924d1',
    storageBucket: 'onenation-hub-924d1.firebasestorage.app',
    iosBundleId: 'com.example.onenationHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJGhoXb-pmNYiR30d9mtgG5ivlgtdFKlc',
    appId: '1:246504893636:web:efc10f7d9572402c5ded91',
    messagingSenderId: '246504893636',
    projectId: 'onenation-hub-924d1',
    authDomain: 'onenation-hub-924d1.firebaseapp.com',
    storageBucket: 'onenation-hub-924d1.firebasestorage.app',
    measurementId: 'G-49VQT9GPMR',
  );

}